### ISSUE TITLE
Germany flag

### ISSUE THREAD

**Issue by Alhamou** [afeld/emoji-css#40] opened 2019-11-02 11:44 UTC
why  i can not find Germany flag ?
here : https://afeld.github.io/emoji-css/

**Comment by djanogly** [comment] 2019-11-05 10:52
Seconded. Was using it, em-de has now changed to the white D on blue background. Would like it back please!

**Comment by Alhamou** [comment] 2019-11-05 11:32
yes please, make it like Germany flag with three colors.

**Comment by afeld** [comment] 2019-11-09 05:59
Duplicate of #39.

**Closed as completed by afeld** 2019-11-09 05:59 UTC
